objc: true
clean: true
sdk: iphonesimulator

theme: ../Themes/apple

module: MobileCenter
module_version: 1.0.0
author: Microsoft Corp
author_url: http://www.microsoft.com

readme: Guides/MobileCenter.md
documentation: ../Guides/[^index]*.md
custom_categories:
  - name: Guides
    children:
    - Installation

umbrella_header: ../../Products/MobileCenter/MobileCenter.framework/Headers/MobileCenter.h
framework_root: ../../Products/MobileCenter/

root_url: http://test.com/sdk/ios/1.0.0
github_url: https://github.com/Microsoft/MobileCenter-SDK-iOS
github_file_prefix: "https://github.com/Microsoft/MobileCenter-SDK-iOS"

skip_undocumented: true

output: Generated/
