objc: true
clean: true
sdk: iphonesimulator

theme: ../Themes/apple

module: MobileCenterAnalytics
module_version: 0.3.3
author: Microsoft Corp
author_url: http://www.microsoft.com

readme: Guides/Analytics.md
documentation: ../Guides/[^index]*.md
custom_categories:
  - name: Guides
    children:
    - Installation

umbrella_header: ../../MobileCenter-SDK-iOS/MobileCenterAnalytics.framework/Headers/MobileCenterAnalytics.h
framework_root: ../../MobileCenter-SDK-iOS
exclude: [../../MobileCenter-SDK-iOS/MobileCenterAnalytics.framework/Headers/MSService.h, ../../MobileCenter-SDK-iOS/MobileCenterAnalytics.framework/Headers/MSServiceAbstract.h]

root_url: http://docs.mobile.azure.com/sdk/ios/
github_url: https://github.com/Microsoft/MobileCenter-SDK-iOS
github_file_prefix: "https://github.com/Microsoft/MobileCenter-SDK-iOS"

skip_undocumented: true

output: Generated/
